name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Altere para "master" se a sua branch principal tiver esse nome

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false # Garante que ele não cancele a fila se você commitar rápido

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Se for React/Vite, geralmente muda para './dist'. Se for HTML puro, deixe '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4